export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const UPDATE_ARTICLE_COMMENTS = 'UPDATE_ARTICLE_COMMENTS'
export const INCREMENT = 'INCREMENT'

export const  CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE'
export const  CHANGE_SELECTION = 'CHANGE_SELECTION'

export const ADD_COMMENT = 'ADD_COMMENT'
